# Generated by Django 4.1.5 on 2023-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom_store", "0002_alter_store_store_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="store_id",
            field=models.CharField(max_length=150),
        ),
    ]
