# Generated by Django 4.1.5 on 2023-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom_store", "0003_alter_store_store_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="store_id",
        ),
        migrations.AddField(
            model_name="store",
            name="store_code",
            field=models.CharField(
                default="<django.db.models.fields.CharField>#1403", max_length=150
            ),
        ),
    ]
