# Generated by Django 4.1.5 on 2023-02-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ecom_store", "0005_alter_store_store_code_alter_store_store_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=50)),
                ("section_number", models.IntegerField(unique=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecom_store.store",
                    ),
                ),
            ],
        ),
    ]
