# Generated by Django 4.1.5 on 2023-02-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecom_store", "0006_storesection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storesection",
            name="section_number",
            field=models.IntegerField(),
        ),
    ]
