# Generated by Django 4.1.5 on 2023-02-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_store', '0008_productcategory_storeproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='store_section',
        ),
        migrations.RemoveField(
            model_name='storesection',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='storesection',
            name='store',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='store_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom_store.storesection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storesection',
            name='section_code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
