# Generated by Django 4.1.7 on 2023-02-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_store', '0009_remove_storeproduct_store_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='product_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
