# Generated by Django 4.1.7 on 2023-02-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomprofile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
