# Generated by Django 4.1.7 on 2023-02-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom_store', '0011_alter_storeproduct_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_code', models.CharField(max_length=15)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_store.storeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('pending', 'PENDING'), ('canceled', 'CANCELED'), ('delivered', 'DELIVERED'), ('confirmed_and_in_route', 'CONFIRMED AND IN ROUTE')], max_length=30)),
                ('confirmed_delivery_date', models.DateField()),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_sales.salesorder')),
            ],
        ),
    ]
