# Generated by Django 4.1.7 on 2023-02-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='delivery_date',
            field=models.DateField(default="2021-10-10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom_sales.salesorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorderconfirmation',
            name='order_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('canceled', 'CANCELED'), ('delivered', 'DELIVERED'), ('confirmed_and_in_route', 'CONFIRMED AND IN ROUTE')], default=('pending', 'PENDING'), max_length=30),
        ),
    ]
